# sample for postgres stack
#
version: '3.1'

services:
  db:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /root/docker/volumes/postgres:/var/lib/postgresql/data

  adminer:
   image: adminer
   restart: always
   ports:
     - "5532:8080"
